name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  draft_release:
    if: github.repository == '$REPO$'
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        name: Draft
        with:
          config-name: $TEMPLATE_NAME$
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}